modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "iridium_exporter"
version = "${version}"
displayName = "Iridium Exporter"
authors = "xEobard_Thawne"
description = '''
This mod exports files that the program Iridium uses.
'''
#logoFile = ""

[[dependencies.iridium_exporter]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iridium_exporter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iridium_exporter]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
